on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  aws_cdk:
    runs-on: "ubuntu-20.04"
    env:
      iac-dir: ./data_ingestion_infra

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Setup Node and NPM
        uses: actions/setup-node@v2
        with:
          node-version: "16.15.1"
    
      - name : AWS Configure
        uses: aws-actions/configure-aws-credentials@master
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: "us-east-1"
      
      - name: Install AWS CDK
        run: npm i aws-cdk
        working-directory: ${{ env.iac-dir }}
      
      - name: CDK bootstrap
        run: yarn cdk bootstrap
        working-directory: ${{ env.iac-dir }}

      - name: Deploy Application
        run: yarn cdk deploy DataIngestionInfraStack --require-approval never
        working-directory: ${{ env.iac-dir }}
      
      - name: Get URL API
        run: aws cloudformation describe-stacks --stack-name DataIngestionInfraStack --query "Stacks[?StackName=='DataIngestionInfraStack'][].Outputs[?OutputKey=='FunctionURLAPI'].OutputValue" --no-paginate --output text

      - name: Deploy Traffic
        run: yarn cdk deploy LoadTesterInfraStack --require-approval never
        working-directory: ${{ env.iac-dir }}
      
      - name: Upload Log Archive to S3
        run: cd .. && ls
